site_name: Obsidian Fantasy Calendar
repo_url: https://github.com/valentine195/obsidian-fantasy-calendar
edit_uri: edit/master/docs/docs/
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
theme:
  font:
    text: Inter
    code: Roboto Mono
  name: material
  palette:
    primary: blue grey
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
nav:
  - Overview: 'index.md'
  - 'Getting Started': 'getting-started/index.md'
  - 'Using the Plugin': 'using-the-plugin/index.md'
  - Events: 'events/index.md'
  - Configuration: 'settings/index.md'
  - Changelog: 'CHANGELOG.md'